### ISSUE TITLE
Cannot use custom theme as default theme

### ISSUE THREAD

**Issue by Overruler** [jeeeyul/eclipse-themes#222]
I have exported a custom theme as an EPF file and then have the following in a plugin.xml:

    <extension
        point="net.jeeeyul.eclipse.themes.preset">
      <preset
            epf="Dark Atoll.epf"
            id="evening.dark_atoll"
            name="Dark Atoll">
         <description>
            Dark Atoll Preset
         </description>
      </preset>
    </extension>

To have this theme appear as soon as a new unused workspace is opened, I have the following in my product definition:

		  <property
				name="cssTheme"
				value="net.jeeeyul.eclipse.themes.custom">

and the following in plugin_customization.ini:

net.jeeeyul.eclipse.themes.ui/MEMENTO__LAST_CHOOSED_PRESET=evening.dark_atoll

However, after starting Eclipse in a new workspace the Minimalist (Default) theme is still used, even though the preset selector in the toolbar shows the Dark Atoll theme to be active. Switching the theme manually to some other theme and then back to the Dark Atoll theme finally displays the theme correctly.

**Comment by Overruler** [comment]
I'm not sure at which point the MEMENTO__LAST_CHOOSED_PRESET from plugin_customization.ini becomes visible. It isn't visible during initialization of preference store defaults and I couldn't see it with an IPropertyChangeListener either, but it is visible once the workbench is up and running.

For now I've rolled back the product changes and am just overwriting the presets/default/default.epf file contents with my own theme. This works but it is inviting a merge conflict as soon as the Minimalist preset changes.

**Comment by jeeeyul** [comment]
In drop down menu on the top right corner in settings page,
You can find **Show EPF**.
All of them should have to be defined as plugin_customiztion.ini.

However, I suggest using your own custom css. See [example E4 Product](https://github.com/jeeeyul/eclipse-themes/tree/master/net.jeeeyul.eclipse.themes.test.e4app).
