### ISSUE TITLE
can't install on fresh eclipse luna install 

### ISSUE THREAD

**Issue by frank-dspeed** [jeeeyul/eclipse-themes#223]
Cannot complete the install because one or more required items could not be found.
  Software being installed: Jeeeyul's Themes 2.2.0.I20141210-114528 (net.jeeeyul.eclipse.themes.feature.feature.group 2.2.0.I20141210-114528)
  Missing requirement: Jeeeyul's Themes 2.2.0.I20141210-114528 (net.jeeeyul.eclipse.themes.feature.feature.group 2.2.0.I20141210-114528) requires 'org.eclipse.e4.ui.workbench.renderers.swt 0.11.0' but it could not be found

**Comment by paulvi** [comment]
What Eclipse? 4.4.1a (SR1a) ?

**Comment by jeeeyul** [comment]
@frank-dspeed I could not reproduce problem that you've report. Are you sure that you are using Eclipse Luna?
