### ISSUE TITLE
Can't share my exported theme

### ISSUE THREAD

**Issue by phackwer** [jeeeyul/eclipse-themes#228]
I have just made a perfect all black theme and ust can't share it at the store. 

Here's the EPF. It keep telling me it's "invalid" How? It was exported completely by your tool.

#Jeeeyul's Eclipse Themes Preset
#Fri Mar 06 02:08:03 BRT 2015
ACTIVE_PART_STACK__CLOSE_BUTTON_COLOR=0.0, 0.0, 0.8031915
INACTIVE_PART_STACK__HOVER_TEXT_COLOR=180.0, 0.040609, 0.772549
WINDOW__STATUS_BAR_FILL_COLOR=0.0, 0.0, 0.06666667, 0|0.0, 0.0, 0.06666667, 100
WINDOW__PERSPECTIVE_SWITCHER_TEXT_COLOR=24.532019, 0.0, 1.0
ACTIVE_PART_STACK__HOVER_FILL_COLOR=0.0, 0.0, 0.2712766, 0|0.0, 0.0, 0.180392, 100
INACTIVE_PART_STACK__UNSELECTED_BORDER_COLOR=24.532019, 0.0, 0.6117021, 0|24.532019, 0.0, 0.611702, 100
INACTIVE_PART_STACK__SELECTED_BORDER_COLOR=24.532019, 0.825203, 0.964706, 0|24.532019, 0.825203, 0.964706, 100
FORMS__FORM_HEADING_TITLE_COLOR=211.57895, 0.0, 1.0
ACTIVE_PART_STACK__UNSELECTED_BORDER_SHOW=
ACTIVE_PART_STACK__BORDER_COLOR=24.532019, 0.82520324, 0.9647059, 0|24.532019, 0.825203, 0.964706, 100
ACTIVE_PART_STACK__CHEVRON_COLOR=0.0, 0.0, 0.84042555
FORMS__SECTION_HEADER_TINT_COLOR=210.0, 0.07968127, 0.9843137
INACTIVE_PART_STACK__UNSELECTED_BORDER_SHOW=
ACTIVE_PART_STACK__UNSELECTED_TEXT_SHADOW_POSITION=0, 0
INACTIVE_PART_STACK__BODY_BACKGROUND_COLOR=0.0, 0.0, 0.0
EDITORS_PART_STACK__BORDER_SHOW=
FORMS__FORM_HEADING_BORDER_2_COLOR=210.90909, 0.0, 0.0
FORMS__SECTION_HEADER_ACTIVE_TITLE_COLOR=211.57895, 0.25531915, 0.64893615
INACTIVE_PART_STACK__CLOSE_BUTTON_COLOR=0.0, 0.0, 0.8031915
INACTIVE_PART_STACK__SELECTED_TEXT_SHADOW_COLOR=0.0, 0.0, 0.0
FORMS__SECTION_HEADER_TITLE_COLOR=211.57895, 0.30158728, 0.49411765
INACTIVE_PART_STACK__HOVER_TEXT_SHADOW_POSITION=0, 0
LAYOUT__CONTENT_PADDING=
ACTIVE_PART_STACK__SELECTED_FILL_COLOR=24.532019, 0.0, 0.26666668, 0|0.0, 0.0, 0.26666668, 100
INACTIVE_PART_STACK__UNSELECTED_FILL_COLOR=0.0, 0.0, 0.0, 0|0.0, 0.0, 0.0, 100
LAYOUT__MINIMUM_CHARACTERS_FOR_EDITORS=8
LAYOUT__CLOSE_BUTTON_VERTICAL_ALIGNMENT=1
FORMS__FORM_HEADING_BORDER_1_COLOR=0.0, 0.0, 0.0
FORMS__ACTIVE_HYPER_LINK_COLOR=238.94273, 0.88829786, 0.60638297
INACTIVE_PART_STACK__HOVER_FILL_COLOR=0.0, 0.0, 0.2712766, 0|0.0, 0.0, 0.180392, 100
ACTIVE_PART_STACK__BORDER_SHOW=
WINDOW__PERSPECTIVE_SWITCHER_FILL_COLOR=0.0, 0.0, 0.06666667, 0|0.0, 0.0, 0.06666667, 100
LAYOUT__TAB_ITEM_PADDING=10
WINDOW__SASH_WIDTH=6
EMPTY_PART_STACK__BORDER_COLOR=0.0, 0.0, 0.56383, 0|0.0, 0.0, 0.5638298, 100
ACTIVE_PART_STACK__UNSELECTED_TEXT_COLOR=0.0, 0.0, 0.7712766
INACTIVE_PART_STACK__CHEVRON_COLOR=0.0, 0.0, 0.84042555
INACTIVE_PART_STACK__CLOSE_BUTTON_ACTIVE_COLOR=0.0, 0.87765956, 0.86702126
EMPTY_PART_STACK__BORDER_SHOW=
ACTIVE_PART_STACK__HEADER_BACKGROUND_COLOR=0.0, 0.0, 0.13333334, 0|0.0, 0.0, 0.13333334, 100|0.0, 0.0, 0.13333334, 100
OTHERS__DRAG_FEEDBACK_ALPHA=127
INACTIVE_PART_STACK__CLOSE_BUTTON_LINE_WIDTH=2
TEXT_EDITOR__RULER_COLOR=300.0, 0.0, 0.9411765
ACTIVE_PART_STACK__HOVER_BORDER_COLOR=24.532019, 0.0, 0.6117021, 0|24.532019, 0.0, 0.611702, 100
OTHERS__USER_CSS=.MPart Composite,\n.MPart Tree,\n.MPart Table,\n.MPart CTabFolder\n{\n\tbackground-color \: black;\n\tcolor \: \#666666;\n}\n\n.MPart.Editor Canvas{\n\tbackground-color\: black;\n}
INACTIVE_PART_STACK__HOVER_BORDER_SHOW=
LAYOUT__TAB_HEIGHT=25
LAYOUT__TRUNCATE_TAB_ITEMS=
OTHERS__MRU_VISIBLE=true
WINDOW__BACKGROUND_COLOR=0.0, 0.0, 0.06666667
WINDOW__TOOLBAR_FILL_COLOR=0.0, 0.0, 0.06666667, 0|0.0, 0.0, 0.06666667, 100
LAYOUT__TAB_SPACING=
WINDOW__MARGINS=4, 4, 4, 4
ACTIVE_PART_STACK__SELECTED_BORDER_COLOR=24.532019, 0.825203, 0.964706, 0|24.532019, 0.825203, 0.964706, 100
ACTIVE_PART_STACK__HOVER_FILL=true
EDITORS_PART_STACK__FILL_COLOR=0.0, 0.0, 0.16078432, 0|0.0, 0.0, 0.160784, 0|0.0, 0.0, 0.160784, 100
LAYOUT__SHADOW_COLOR=0.0, 0.0, 0.0
LAYOUT__BORDER_RADIUS=
FORMS__SECTION_HEADER_BORDER_COLOR=210.90909, 0.27160493, 0.9529412
ACTIVE_PART_STACK__BODY_BACKGROUND_COLOR=0.0, 0.0, 0.0
ACTIVE_PART_STACK__CLOSE_BUTTON_ACTIVE_COLOR=0.0, 0.87765956, 0.86702126
INACTIVE_PART_STACK__SELECTED_BORDER_SHOW=
INACTIVE_PART_STACK__UNSELECTED_TEXT_SHADOW_COLOR=0.0, 0.0, 1.0
ACTIVE_PART_STACK__HOVER_TEXT_SHADOW_COLOR=180.0, 0.040609132, 0.77254903
TEXT_EDITOR__UNDER_LINE_COLOR=0.0, 0.0, 0.0
INACTIVE_PART_STACK__BORDER_COLOR=24.532019, 0.82520324, 0.9647059, 0|24.532019, 0.825203, 0.964706, 100
INACTIVE_PART_STACK__HOVER_BORDER_COLOR=24.532019, 0.0, 0.6117021, 0|24.532019, 0.0, 0.611702, 100
INACTIVE_PART_STACK__SELECTED_TEXT_COLOR=0.0, 0.0, 1.0
ACTIVE_PART_STACK__UNSELECTED_TEXT_SHADOW_COLOR=0.0, 0.0, 1.0
LAYOUT__TRUNCATE_EDITORS_TAB_ITEMS_ALSO=true
ACTIVE_PART_STACK__UNSELECTED_FILL_COLOR=0.0, 0.0, 0.0, 0|0.0, 0.0, 0.0, 100
INACTIVE_PART_STACK__UNSELECTED_FILL=
EMPTY_PART_STACK__FILL_COLOR=0.0, 0.0, 0.16078432, 0|0.0, 0.0, 0.0, 0|0.0, 0.0, 0.0, 100
ACTIVE_PART_STACK__UNSELECTED_BORDER_COLOR=24.532019, 0.0, 0.6117021, 0|24.532019, 0.0, 0.611702, 100
INACTIVE_PART_STACK__SELECTED_TEXT_SHADOW_POSITION=0, 0
WINDOW__PERSPECTIVE_SWITCHER_KEY_LINE_COLOR=0.0, 1.0, 0.0
LAYOUT__TAB_ITEM_SPACING=3
LAYOUT__USE_ELLIPSES=
FORMS__FORM_HEADING_BACKGROUND=0.0, 0.0, 0.0, 0|210.0, 0.0, 0.0, 100
WINDOW__STATUS_BAR_TEXT_COLOR=209.18918, 0.0, 1.0
EDITORS_PART_STACK__BORDER_COLOR=24.532019, 0.0, 0.6117021, 0|24.532019, 0.0, 0.611702, 100
ACTIVE_PART_STACK__SELECTED_TEXT_SHADOW_POSITION=0, 0
INACTIVE_PART_STACK__HEADER_BACKGROUND_COLOR=0.0, 0.0, 0.13333334, 0|0.0, 0.0, 0.13333334, 100|0.0, 0.0, 0.13333334, 100
ACTIVE_PART_STACK__HOVER_TEXT_COLOR=180.0, 0.040609, 0.772549
ACTIVE_PART_STACK__UNSELECTED_FILL=
INACTIVE_PART_STACK__UNSELECTED_TEXT_SHADOW_POSITION=0, 0
INACTIVE_PART_STACK__HOVER_FILL=true
TEXT_EDITOR__UNDER_LINE_STYLE=
INACTIVE_PART_STACK__CLOSE_BUTTON_HOVER_COLOR=0.0, 0.5106383, 0.69148934
ACTIVE_PART_STACK__SELECTED_TEXT_SHADOW_COLOR=0.0, 0.0, 0.0
ACTIVE_PART_STACK__HOVER_TEXT_SHADOW_POSITION=0, 0
LAYOUT__MINIMUM_CHARACTERS=1
ACTIVE_PART_STACK__CLOSE_BUTTON_HOVER_COLOR=0.0, 0.5106383, 0.69148934
ACTIVE_PART_STACK__HOVER_BORDER_SHOW=
ACTIVE_PART_STACK__SELECTED_BORDER_SHOW=
ACTIVE_PART_STACK__SELECTED_TEXT_COLOR=0.0, 0.0, 1.0
INACTIVE_PART_STACK__UNSELECTED_TEXT_COLOR=0.0, 0.0, 0.7712766
INACTIVE_PART_STACK__HOVER_TEXT_SHADOW_COLOR=180.0, 0.040609132, 0.77254903
INACTIVE_PART_STACK__BORDER_SHOW=
INACTIVE_PART_STACK__SELECTED_FILL_COLOR=24.532019, 0.0, 0.26666668, 0|0.0, 0.0, 0.26666668, 100
ACTIVE_PART_STACK__CLOSE_BUTTON_LINE_WIDTH=2
FORMS__HYPER_LINK_COLOR=240.0, 1.0, 1.0
LAYOUT__SHOW_SHADOW=
OTHERS__DRAG_FEEDBACK_COLOR=24.705881, 1.0, 1.0

**Comment by jeeeyul** [comment]
Custom CSS(User CSS) is not allowed for safety.

**Comment by phackwer** [comment]
CSS safety? Really?
