### ISSUE TITLE
API change in CSSSWTColorHelper

### ISSUE THREAD

**Issue by scalpel4k** [jeeeyul/eclipse-themes#229]
Hi,

I have created a little patch that uses the new CSSSWTColorHelper.getRGBA() method.

bye Michi

**Comment by scalpel4k** [comment]
diff --git a/net.jeeeyul.eclipse.themes/src/net/jeeeyul/eclipse/themes/css/internal/CSSCompabilityHelper.java b/net.jeeeyul.eclipse.themes/src/net/jeeeyul/eclipse/themes/css/internal/CSSCompabilityHelper.java
index 52f04ac..46982ef 100644
--- a/net.jeeeyul.eclipse.themes/src/net/jeeeyul/eclipse/themes/css/internal/CSSCompabilityHelper.java
+++ b/net.jeeeyul.eclipse.themes/src/net/jeeeyul/eclipse/themes/css/internal/CSSCompabilityHelper.java
@@ -1,20 +1,20 @@
 package net.jeeeyul.eclipse.themes.css.internal;
 
 import java.util.List;
 
-import net.jeeeyul.eclipse.themes.css.internal.handlers.JTabCSSPropertyHandler;
-
 import org.eclipse.e4.ui.css.core.dom.properties.Gradient;
 import org.eclipse.e4.ui.css.core.engine.CSSEngine;
 import org.eclipse.e4.ui.css.swt.helpers.CSSSWTColorHelper;
 import org.eclipse.swt.graphics.Color;
-import org.eclipse.swt.graphics.RGB;
+import org.eclipse.swt.graphics.RGBA;
 import org.eclipse.swt.widgets.Display;
 import org.w3c.dom.css.CSSPrimitiveValue;
 import org.w3c.dom.css.CSSValue;
 import org.w3c.dom.css.CSSValueList;
+
+import net.jeeeyul.eclipse.themes.css.internal.handlers.JTabCSSPropertyHandler;
 
 /**
  * CSS Value Converter for {@link JTabCSSPropertyHandler}
  * 
  * @author Jeeeyul
@@ -70,13 +70,13 @@
 
 				switch (primType) {
 				case CSSPrimitiveValue.CSS_IDENT:
 				case CSSPrimitiveValue.CSS_STRING:
 				case CSSPrimitiveValue.CSS_RGBCOLOR:
-					RGB rgb = CSSSWTColorHelper.getRGB(value);
-					if (rgb != null) {
-						gradient.addRGB(rgb, (CSSPrimitiveValue) value);
+					RGBA rgba = CSSSWTColorHelper.getRGBA(value);
+					if (rgba != null) {
+						gradient.addRGB(rgba.rgb, (CSSPrimitiveValue) value);
 					} else {
 						// check for vertical gradient
 						gradient.setVertical(!value.getCssText().equals("false"));
 					}
 					break;
diff --git a/net.jeeeyul.eclipse.themes/src/net/jeeeyul/eclipse/themes/css/internal/handlers/JStyledTextPropertyHandler.xtend b/net.jeeeyul.eclipse.themes/src/net/jeeeyul/eclipse/themes/css/internal/handlers/JStyledTextPropertyHandler.xtend
index 202b21f..7d3f5fb 100644
--- a/net.jeeeyul.eclipse.themes/src/net/jeeeyul/eclipse/themes/css/internal/handlers/JStyledTextPropertyHandler.xtend
+++ b/net.jeeeyul.eclipse.themes/src/net/jeeeyul/eclipse/themes/css/internal/handlers/JStyledTextPropertyHandler.xtend
@@ -22,19 +22,19 @@
 class JStyledTextPropertyHandler implements ICSSPropertyHandler {
 
 	override applyCSSProperty(Object element, String property, CSSValue value, String pseudo, CSSEngine engine) throws Exception {
 		var compositeElement = element as CompositeElement
 		var composite = compositeElement.nativeWidget as Composite
-		if(!(composite instanceof StyledText)) {
+		if (!(composite instanceof StyledText)) {
 			return false
 		}
 		var styledText = composite as StyledText
 		var els = EditorLineSupport.get(styledText)
 
 		switch (property) {
 			case "jeditor-line-style": {
-				if(value instanceof CSSPrimitiveValue) {
+				if (value instanceof CSSPrimitiveValue) {
 					els.lineStyle = switch (value.cssText) {
 						case "solid": SWT.LINE_SOLID
 						case "dashed": SWT.LINE_DASH
 						case "dotted": SWT.LINE_DOT
 						default: SWT.NONE
@@ -43,25 +43,24 @@
 				} else {
 					false
 				}
 			}
 			case "jeditor-line-color": {
-				var rgb = CSSSWTColorHelper.getRGB(value as CSSValue)
-				if(rgb != null) {
-					els.lineColor = new HSB(rgb.red, rgb.green, rgb.blue)
+				var rgba = CSSSWTColorHelper.getRGBA(value as CSSValue)
+				if (rgba != null) {
+					els.lineColor = new HSB(rgba.rgb);
 					true
 				} else {
 					false
 				}
 			}
-			
-			case "jeditor-range-indicator-color" : {
-				var rgb = CSSSWTColorHelper.getRGB(value as CSSValue)
-				if(rgb != null) {
+			case "jeditor-range-indicator-color": {
+				var rgba = CSSSWTColorHelper.getRGBA(value as CSSValue)
+				if (rgba != null) {
 					var field = DefaultRangeIndicator.getDeclaredField("fgPaletteData");
 					field.setAccessible(true);
-					var paletteData = new PaletteData(newArrayList(rgb, rgb))
+					var paletteData = new PaletteData(newArrayList(rgba.rgb, rgba.rgb))
 					true
 				}
 	}
 		}
 		var styledText = composite as StyledText
 		var els = EditorLineSupport.get(styledText)
 
diff --git a/net.jeeeyul.eclipse.themes/src/net/jeeeyul/eclipse/themes/css/internal/handlers/JTabCSSPropertyHandler.xtend b/net.jeeeyul.eclipse.themes/src/net/jeeeyul/eclipse/themes/css/internal/handlers/JTabCSSPropertyHandler.xtend
index 66b4c7e..922cc46 100644
--- a/net.jeeeyul.eclipse.themes/src/net/jeeeyul/eclipse/themes/css/internal/handlers/JTabCSSPropertyHandler.xtend
+++ b/net.jeeeyul.eclipse.themes/src/net/jeeeyul/eclipse/themes/css/internal/handlers/JTabCSSPropertyHandler.xtend
@@ -30,412 +30,411 @@
 class JTabCSSPropertyHandler implements ICSSPropertyHandler {
 
 	override applyCSSProperty(Object element, String property, CSSValue value, String pseudo, extension CSSEngine engine) throws Exception {
 		var tabFolderElement = element as CTabFolderElement
 		var tabFolder = tabFolderElement.nativeWidget as CTabFolder
-		if(!(tabFolder.renderer instanceof JeeeyulsTabRenderer)) {
+		if (!(tabFolder.renderer instanceof JeeeyulsTabRenderer)) {
 			return false;
 		}
 		var renderer = tabFolder.renderer as JeeeyulsTabRenderer
 		var settings = renderer.settings
 
 		var applied = switch (property) {
 			case "jtab-selected-tab-background": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var grad = CSSCompabilityHelper.getGradient(value as CSSValueList)
 					var colors = CSSCompabilityHelper.getSWTColors(grad, tabFolder.display, engine)
 					var percents = CSSCompabilityHelper.getPercents(grad)
 					tabFolder.setSelectionBackground(colors, percents, true)
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
+				} else if (value instanceof CSSPrimitiveValue) {
 					var newColor = engine.convert(value, typeof(Color), tabFolder.display) as Color
 					tabFolder.setSelectionBackground(#[newColor, newColor], #[100], true)
 					true
 				} else {
 					false
 				}
 			}
 			case "jtab-header-background": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var grad = CSSCompabilityHelper.getGradient(value as CSSValueList)
 					var colors = CSSCompabilityHelper.getSWTColors(grad, tabFolder.display, engine)
 					var percents = CSSCompabilityHelper.getPercents(grad)
 					tabFolder.setBackground(colors, percents, true)
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
+				} else if (value instanceof CSSPrimitiveValue) {
 					var newColor = engine.convert(value, typeof(Color), tabFolder.display) as Color
 					tabFolder.setBackground(#[newColor, newColor], #[100], true)
 					true
 				} else {
 					false
 				}
 			}
 			case "jtab-border-color": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var grad = CSSCompabilityHelper.getGradient(value as CSSValueList)
 					settings.borderColors = grad.toHSBArray()
 					settings.borderPercents = CSSSWTColorHelper.getPercents(grad)
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
-					var rgb = CSSSWTColorHelper.getRGB(value)
-					if(rgb != null) {
-						var hsb = new HSB(rgb)
+				} else if (value instanceof CSSPrimitiveValue) {
+					var rgba = CSSSWTColorHelper.getRGBA(value)
+					if (rgba != null) {
+						var hsb = new HSB(rgba.rgb)
 						settings.borderColors = #[hsb, hsb]
 						settings.borderPercents = #[100]
 						true
-					} else if(value.cssText == "none") {
+					} else if (value.cssText == "none") {
 						settings.borderColors = null
 						true
 					} else {
 						false
 					}
 				} else {
 					false
 				}
 			}
 			case "jtab-selected-border-color": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var grad = CSSCompabilityHelper.getGradient(value as CSSValueList)
 					settings.selectedBorderColors = grad.toHSBArray()
 					settings.selectedBorderPercents = CSSSWTColorHelper.getPercents(grad)
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
-					var rgb = CSSSWTColorHelper.getRGB(value)
-					if(rgb != null) {
-						var hsb = new HSB(rgb)
+				} else if (value instanceof CSSPrimitiveValue) {
+					var rgba = CSSSWTColorHelper.getRGBA(value)
+					if (rgba != null) {
+						var hsb = new HSB(rgba.rgb)
 						settings.selectedBorderColors = #[hsb, hsb]
 						settings.selectedBorderPercents = #[100]
 						true
-					} else if(value.cssText == "none") {
+					} else if (value.cssText == "none") {
 						settings.selectedBorderColors = null
 						true
 					} else {
 						false
 					}
 				} else {
 					false
 				}
 			}
 			case "jtab-unselected-border-color": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var grad = CSSCompabilityHelper.getGradient(value as CSSValueList)
 					settings.unselectedBorderColors = grad.toHSBArray()
 					settings.unselectedBorderPercents = CSSSWTColorHelper.getPercents(grad)
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
-					var rgb = CSSSWTColorHelper.getRGB(value)
-					if(rgb != null) {
-						var hsb = new HSB(rgb)
+				} else if (value instanceof CSSPrimitiveValue) {
+					var rgba = CSSSWTColorHelper.getRGBA(value)
+					if (rgba != null) {
+						var hsb = new HSB(rgba.rgb)
 						settings.unselectedBorderColors = #[hsb, hsb]
 						settings.unselectedBorderPercents = #[100]
 						true
-					} else if(value.cssText == "none") {
+					} else if (value.cssText == "none") {
 						settings.unselectedBorderColors = null
 						true
 					} else {
 						false
 					}
 				} else {
 					false
 				}
 			}
 			case "jtab-border-radius": {
-				if(value instanceof CSSPrimitiveValue) {
+				if (value instanceof CSSPrimitiveValue) {
 					var radius = (value as CSSPrimitiveValue).getFloatValue(CSSPrimitiveValue.CSS_PX) as int
 					settings.borderRadius = radius
 					true
 				} else {
 					false
 				}
 			}
 			case "jtab-spacing": {
-				if(value instanceof CSSPrimitiveValue) {
+				if (value instanceof CSSPrimitiveValue) {
 					var tabSpacing = (value as CSSPrimitiveValue).getFloatValue(CSSPrimitiveValue.CSS_PX) as int
 					settings.tabSpacing = tabSpacing
 					true
 				} else {
 					false
 				}
 			}
 			case "jtab-close-button-color": {
-				var rgb = CSSSWTColorHelper.getRGB(value as CSSValue)
-				if(rgb != null) {
-					var hsb = new HSB(rgb.red, rgb.green, rgb.blue)
+				var rgba = CSSSWTColorHelper.getRGBA(value as CSSValue);
+				if (rgba != null) {
+					var hsb = new HSB(rgba.rgb.red, rgba.rgb.green, rgba.rgb.blue)
 					settings.closeButtonColor = hsb
 				} else {
 					settings.closeButtonColor = null
 				}
 				true
 			}
 			case "jtab-close-button-line-width": {
-				if(value instanceof CSSPrimitiveValue) {
+				if (value instanceof CSSPrimitiveValue) {
 					var lineWidth = (value as CSSPrimitiveValue).getFloatValue(CSSPrimitiveValue.CSS_PX) as int
 					settings.closeButtonLineWidth = lineWidth
 					true
 				} else {
 					false
 				}
 			}
 			case "jtab-hover-color": {
-				var rgb = CSSSWTColorHelper.getRGB(value as CSSValue)
-				if(rgb != null) {
-					var hsb = new HSB(rgb.red, rgb.green, rgb.blue)
+				var rgba = CSSSWTColorHelper.getRGBA(value as CSSValue);
+				if (rgba != null) {
+					var hsb = new HSB(rgba.rgb.red, rgba.rgb.green, rgba.rgb.blue)
 					settings.hoverForgroundColor = hsb
 				} else {
 					settings.hoverForgroundColor = null
 				}
 				true
 			}
 			case "jtab-hover-border-color": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var grad = CSSCompabilityHelper.getGradient(value as CSSValueList)
 					settings.hoverBorderColors = grad.toHSBArray()
 					settings.hoverBorderPercents = CSSSWTColorHelper.getPercents(grad)
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
-					var rgb = CSSSWTColorHelper.getRGB(value)
-					if(rgb != null) {
-						var hsb = new HSB(rgb)
+				} else if (value instanceof CSSPrimitiveValue) {
+					var rgba = CSSSWTColorHelper.getRGBA(value);
+					if (rgba != null) {
+						var hsb = new HSB(rgba.rgb)
 						settings.hoverBorderColors = #[hsb, hsb]
 						settings.hoverBorderPercents = #[100]
 						true
-					} else if(value.cssText == "none") {
+					} else if (value.cssText == "none") {
 						settings.hoverBorderColors = null
 						true
 					} else {
 						false
 					}
 				} else {
 					false
 				}
 			}
 			case "jtab-close-button-hot-color": {
-				var rgb = CSSSWTColorHelper.getRGB(value as CSSValue)
-				if(rgb != null) {
-					var hsb = new HSB(rgb.red, rgb.green, rgb.blue)
+				var rgba = CSSSWTColorHelper.getRGBA(value as CSSValue)
+				if (rgba != null) {
+					var hsb = new HSB(rgba.rgb.red, rgba.rgb.green, rgba.rgb.blue)
 					settings.closeButtonHotColor = hsb
 				} else {
 					settings.closeButtonHotColor = null
 				}
 				true
 			}
 			case "jtab-close-button-active-color": {
-				var rgb = CSSSWTColorHelper.getRGB(value as CSSValue)
-				if(rgb != null) {
-					var hsb = new HSB(rgb.red, rgb.green, rgb.blue)
+				var rgba = CSSSWTColorHelper.getRGBA(value as CSSValue);
+				if (rgba != null) {
+					var hsb = new HSB(rgba.rgb.red, rgba.rgb.green, rgba.rgb.blue)
 					settings.closeButtonActiveColor = hsb
 				} else {
 					settings.closeButtonActiveColor = null
 				}
 				true
 			}
 			case "jtab-unselected-tabs-background": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var grad = CSSCompabilityHelper.getGradient(value as CSSValueList)
 					settings.unselectedBackgroundColors = grad.toHSBArray()
 					settings.unselectedBackgroundPercents = CSSSWTColorHelper.getPercents(grad)
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
-					var rgb = CSSSWTColorHelper.getRGB(value)
-					if(rgb != null) {
-						var hsb = new HSB(rgb)
+				} else if (value instanceof CSSPrimitiveValue) {
+					var rgba = CSSSWTColorHelper.getRGBA(value)
+					if (rgba != null) {
+						var hsb = new HSB(rgba.rgb);
 						settings.unselectedBackgroundColors = #[hsb, hsb]
 						settings.unselectedBackgroundPercents = #[100]
 						true
-					} else if(value.cssText == "none") {
+					} else if (value.cssText == "none") {
 						settings.unselectedBackgroundColors = null
 						true
 					} else {
 						false
 					}
 				} else {
 					false
 				}
 			}
 			case "jtab-hover-tabs-background": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var grad = CSSCompabilityHelper.getGradient(value as CSSValueList)
 					settings.hoverBackgroundColors = grad.toHSBArray()
 					settings.hoverBackgroundPercents = CSSSWTColorHelper.getPercents(grad)
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
-					var rgb = CSSSWTColorHelper.getRGB(value)
-					if(rgb != null) {
-						var hsb = new HSB(rgb)
+				} else if (value instanceof CSSPrimitiveValue) {
+					var rgba = CSSSWTColorHelper.getRGBA(value);
+					if (rgba != null) {
+						var hsb = new HSB(rgba.rgb)
 						settings.hoverBackgroundColors = #[hsb, hsb]
 						settings.hoverBackgroundPercents = #[100]
 						true
-					} else if(value.cssText == "none") {
+					} else if (value.cssText == "none") {
 						settings.hoverBackgroundColors = null
 						true
 					} else {
 						false
 					}
 				} else {
 					false
 				}
 			}
 			case "jtab-margin": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var insets = (value as CSSValueList).toInset()
 					settings.margins = insets
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
+				} else if (value instanceof CSSPrimitiveValue) {
 					var int margin = (value as CSSPrimitiveValue).getFloatValue(CSSPrimitiveValue.CSS_PX) as int
 					settings.margins = new Rectangle(margin, margin, margin, margin);
 					true
 				} else {
 					false
 				}
 			}
 			case "jtab-padding": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var insets = (value as CSSValueList).toInset()
 					settings.paddings = insets
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
+				} else if (value instanceof CSSPrimitiveValue) {
 					var int margin = (value as CSSPrimitiveValue).getFloatValue(CSSPrimitiveValue.CSS_PX) as int
 					settings.paddings = new Rectangle(margin, margin, margin, margin);
 					true
 				} else {
 					false
 				}
 			}
 			case "jtab-shadow-color": {
-				var rgb = CSSSWTColorHelper.getRGB(value as CSSValue)
-				if(rgb != null) {
-					var hsb = new HSB(rgb.red, rgb.green, rgb.blue)
+				var rgba = CSSSWTColorHelper.getRGBA(value as CSSValue)
+				if (rgba != null) {
+					var hsb = new HSB(rgba.rgb.red, rgba.rgb.green, rgba.rgb.blue)
 					settings.shadowColor = hsb
 				} else {
 					settings.shadowColor = null
 				}
 				true
 			}
 			case "jtab-shadow-position": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var position = (value as CSSValueList).toPoint()
 					settings.shadowPosition = position
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
+				} else if (value instanceof CSSPrimitiveValue) {
 					var int v = (value as CSSPrimitiveValue).getFloatValue(CSSPrimitiveValue.CSS_PX) as int
 					settings.shadowPosition = new Point(v, v)
 					true
 				} else {
 					false
 				}
 			}
 			case "jtab-shadow-radius": {
-				if(value instanceof CSSPrimitiveValue) {
+				if (value instanceof CSSPrimitiveValue) {
 					var v = (value as CSSPrimitiveValue).getFloatValue(CSSPrimitiveValue.CSS_PX) as int
 					settings.shadowRadius = v;
 					true
 				} else {
 					false
 				}
 			}
 			case "jtab-selected-text-shadow-color": {
-				var rgb = CSSSWTColorHelper.getRGB(value as CSSValue)
-				if(rgb != null) {
-					var hsb = new HSB(rgb.red, rgb.green, rgb.blue)
+				var rgba = CSSSWTColorHelper.getRGBA(value as CSSValue)
+				if (rgba != null) {
+					var hsb = new HSB(rgba.rgb.red, rgba.rgb.green, rgba.rgb.blue)
 					settings.selectedTextShadowColor = hsb
 				} else {
 					settings.selectedTextShadowColor = null
 				}
 				true
 			}
 			case "jtab-selected-text-shadow-position": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var position = (value as CSSValueList).toPoint()
 					settings.selectedTextShadowPosition = position
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
+				} else if (value instanceof CSSPrimitiveValue) {
 					var int v = (value as CSSPrimitiveValue).getFloatValue(CSSPrimitiveValue.CSS_PX) as int
 					settings.selectedTextShadowPosition = new Point(v, v)
 					true
 				} else {
 					false
 				}
 			}
 			case "jtab-unselected-text-shadow-color": {
-				var rgb = CSSSWTColorHelper.getRGB(value as CSSValue)
-				if(rgb != null) {
-					var hsb = new HSB(rgb.red, rgb.green, rgb.blue)
+				var rgba = CSSSWTColorHelper.getRGBA(value as CSSValue)
+				if (rgba != null) {
+					var hsb = new HSB(rgba.rgb.red, rgba.rgb.green, rgba.rgb.blue)
 					settings.unselectedTextShadowColor = hsb
 				} else {
 					settings.unselectedTextShadowColor = null
 				}
 				true
 			}
 			case "jtab-unselected-text-shadow-position": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var position = (value as CSSValueList).toPoint()
 					settings.unselectedTextShadowPosition = position
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
+				} else if (value instanceof CSSPrimitiveValue) {
 					var int v = (value as CSSPrimitiveValue).getFloatValue(CSSPrimitiveValue.CSS_PX) as int
 					settings.unselectedTextShadowPosition = new Point(v, v)
 					true
 				} else {
 					false
 				}
 			}
 			case "jtab-hover-text-shadow-color": {
-				var rgb = CSSSWTColorHelper.getRGB(value as CSSValue)
-				if(rgb != null) {
-					var hsb = new HSB(rgb.red, rgb.green, rgb.blue)
+				var rgba = CSSSWTColorHelper.getRGBA(value as CSSValue)
+				if (rgba != null) {
+					var hsb = new HSB(rgba.rgb.red, rgba.rgb.green, rgba.rgb.blue)
 					settings.hoverTextShadowColor = hsb
 				} else {
 					settings.hoverTextShadowColor = null
 				}
 				true
 			}
 			case "jtab-hover-text-shadow-position": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var position = (value as CSSValueList).toPoint()
 					settings.hoverTextShadowPosition = position
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
+				} else if (value instanceof CSSPrimitiveValue) {
 					var int v = (value as CSSPrimitiveValue).getFloatValue(CSSPrimitiveValue.CSS_PX) as int
 					settings.hoverTextShadowPosition = new Point(v, v)
 					true
 				} else {
 					false
 				}
 			}
 			case "jtab-item-padding": {
-				if(value instanceof CSSValueList) {
+				if (value instanceof CSSValueList) {
 					var insets = (value as CSSValueList).toInset()
 					settings.tabItemPaddings = insets
 					true
-				} else if(value instanceof CSSPrimitiveValue) {
+				} else if (value instanceof CSSPrimitiveValue) {
 					var int margin = (value as CSSPrimitiveValue).getFloatValue(CSSPrimitiveValue.CSS_PX) as int
 					settings.tabItemPaddings = new Rectangle(margin, margin, margin, margin);
 					true
 				} else {
 					false
 				}
 			}
 			case "jtab-item-horizontal-spacing": {
-				if(value instanceof CSSPrimitiveValue) {
+				if (value instanceof CSSPrimitiveValue) {
 					var radius = (value as CSSPrimitiveValue).getFloatValue(CSSPrimitiveValue.CSS_PX) as int
 					settings.tabItemHorizontalSpacing = radius
 					true
 				} else {
 					false
 				}
 			}
 			case "jtab-chevron-color": {
-				var rgb = CSSSWTColorHelper.getRGB(value as CSSValue)
-				if(rgb != null) {
-					var hsb = new HSB(rgb.red, rgb.green, rgb.blue)
+				var rgba = CSSSWTColorHelper.getRGBA(value as CSSValue);
+				if (rgba != null) {
+					var hsb = new HSB(rgba.rgb.red, rgba.rgb.green, rgba.rgb.blue)
 					settings.chevronColor = hsb
 				} else {
 					settings.chevronColor = null
 				}
 				true
 			}
-			
 			case "jtab-truncate-tab-items": {
 				var truncateTabItems = engine.convert(value, typeof(Boolean), tabFolder.display) as Boolean
 				settings.truncateTabItems = truncateTabItems
 				true
 			}
@@ -443,31 +442,30 @@
 				var useEllipse = engine.convert(value, typeof(Boolean), tabFolder.display) as Boolean
 				settings.useEllipses = useEllipse
 				true
 			}
 			case "jtab-minimum-characters": {
-				if(value instanceof CSSPrimitiveValue) {
+				if (value instanceof CSSPrimitiveValue) {
 					var v = (value as CSSPrimitiveValue).getFloatValue(CSSPrimitiveValue.CSS_NUMBER) as int
 					settings.minimumCharacters = v;
 					true
 				} else {
 					false
 				}
 			}
-			case "jtab-close-button-alignment" : {
-				if(value instanceof Measure){
+			case "jtab-close-button-alignment": {
+				if (value instanceof Measure) {
 					var measureValue = value as Measure
-					try{
+					try {
 						var alignment = VerticalAlignment.fromCSSValue(measureValue.stringValue)
 						settings.closeButtonAlignment = alignment
-					}catch(IllegalArgumentException e){
+					} catch (IllegalArgumentException e) {
 						return false
 					}
 				}
 				false
 			}
-			
 			default: {
 				false
 			}
 		}
 
@@ -477,11 +475,11 @@
 	override retrieveCSSProperty(Object element, String property, String pseudo, CSSEngine engine) throws Exception {
 		val extension JTabRendererHelper = new JTabRendererHelper()
 
 		var tabFolderElement = element as CTabFolderElement
 		var tabFolder = tabFolderElement.nativeWidget as CTabFolder
-		if(!(tabFolder.renderer instanceof JeeeyulsTabRenderer)) {
+		if (!(tabFolder.renderer instanceof JeeeyulsTabRenderer)) {
 			return null;
 		}
 		var renderer = tabFolder.renderer as JeeeyulsTabRenderer
 		var settings = renderer.settings
 
@@ -511,12 +509,14 @@
 				toHTML(settings.unselectedBackgroundColors, settings.unselectedBackgroundPercents)
 			case "jtab-hover-tabs-background":
 				toHTML(settings.hoverBackgroundColors, settings.hoverBackgroundPercents)
 			case "jtab-hover-color":
 				settings.hoverForgroundColor.safeHTML
-			case "jtab-margin": '''«settings.margins.y»px «settings.margins.width»px «settings.margins.height»px «settings.margins.x»px'''
-			case "jtab-padding": '''«settings.paddings.y»px «settings.paddings.width»px «settings.paddings.height»px «settings.paddings.x»px'''
+			case "jtab-margin": '''«settings.margins.y»px «settings.margins.width»px «settings.margins.height»px «settings.
+				margins.x»px'''
+			case "jtab-padding": '''«settings.paddings.y»px «settings.paddings.width»px «settings.paddings.height»px «settings.
+				paddings.x»px'''
 			case "jtab-shadow-color":
 				settings.shadowColor.safeHTML
 			case "jtab-shadow-radius": '''«settings.shadowRadius»px'''
 			case "jtab-shadow-position":
 				settings.shadowPosition.safeHTML
@@ -533,45 +533,46 @@
 			case "jtab-hover-text-shadow-position":
 				settings.hoverTextShadowPosition.safeHTML
 			case "jtab-item-padding": '''0px «settings.tabItemPaddings.width»px 0px «settings.tabItemPaddings.x»px'''
 			case "jtab-item-horizontal-spacing": '''«settings.tabItemHorizontalSpacing»px'''
 			case "jtab-chevron-color": '''«settings.chevronColor.toHTMLCode»'''
-			case "jtab-truncate-tab-items" : '''«settings.truncateTabItems»'''
+			case "jtab-truncate-tab-items": '''«settings.truncateTabItems»'''
 			case "jtab-use-ellipses": '''«settings.useEllipses»'''
-			case "jtab-minimum-characters" : '''«settings.minimumCharacters»'''
-			case "jtab-close-button-alignment" : settings.closeButtonAlignment.CSSValue
+			case "jtab-minimum-characters": '''«settings.minimumCharacters»'''
+			case "jtab-close-button-alignment":
+				settings.closeButtonAlignment.CSSValue
 			default:
 				null
 		}
 	}
 
 	def private String safeHTML(HSB hsb) {
-		if(hsb == null) {
+		if (hsb == null) {
 			"none"
 		} else {
 			hsb.toHTMLCode
 		}
 	}
 
 	def private String safeHTML(Point point) {
-		if(point == null) {
+		if (point == null) {
 			"none"
 		} else {
 			'''«point.x»px «point.y»px'''
 		}
 	}
 
 	def private toHTML(HSB[] colors, int[] percents) {
-		if(colors == null || percents == null) {
+		if (colors == null || percents == null) {
 			return "none";
 		} else {
 			return '''«colors.join(' ')[it.toHTMLCode]» «percents.join(" ")[it + "%"]»'''
 		}
 	}
 
 	def private toHTML(Color[] colors, int[] percents) {
-		if(colors == null || percents == null) {
+		if (colors == null || percents == null) {
 			return "none";
 		} else {
 			return '''«colors.join(' ')[new HSB(it.RGB).toHTMLCode]» «percents.join(" ")[it + "%"]»'''
 		}
 	}
@@ -609,11 +610,11 @@
 		}
 		return new Point(x, y)
 	}
 
 	def private int asPX(CSSValue value) {
-		if(value instanceof CSSPrimitiveValue) {
+		if (value instanceof CSSPrimitiveValue) {
 			return (value as CSSPrimitiveValue).getFloatValue(CSSPrimitiveValue.CSS_PX) as int
 		}
 
 		return 0
 	}

**Comment by scalpel4k** [comment]
sorry for this weird "patch", but I couldn't find a quick solution for adding a file to the issue.

**Comment by paulvi** [comment]
make Pull Request with GitHUb https://help.github.com/articles/using-pull-requests/

**Comment by Mikanoshi** [comment]
Without this patch Eclipse Themes are completely broken, can someone release it?) I have no idea how to build a plugin...

**Comment by scalpel4k** [comment]
a merge request is actually in issue #230, but your comment remains more than true

**Comment by jeeeyul** [comment]
I'm on testing, I will release it as fast as I can.

**Comment by jeeeyul** [comment]
@Mikanoshi @scalpel4k Can you let me know which version of the Eclipse do I have to test with? (or changed dependency plugin and version)

**Comment by Mikanoshi** [comment]
Any version with the latest org.eclipse.e4.ui.css.swt 0.11.200.v20150313-1341

**Comment by jeeeyul** [comment]
@Mikanoshi is `org.eclipse.e4.ui.css.swt 0.11.200.v20150313-1341` part of the eclipse 4.5M6?
I have tested with eclipse 4.4SR2 (currently latest release), there was no problem.

I think that I have to support both of version 4.4 and 4.5.

**Comment by Mikanoshi** [comment]
Yes, it's Mars Milestone 6 (4.5.0M6)

**Comment by jeeeyul** [comment]
@Mikanoshi Thanks :+1:

**Comment by pwilkin** [comment]
Any plans to make a branched release for Mars M6? This indeed breaks the plugin totally under the new API.

**Comment by lowne** [comment]
@scalpel4k could you share the bare jars as an interim solution? A glimpse at the required infrastructure rapidly dissuaded me from trying to build it myself...

**Comment by takahashikzn** [comment]
@lowne 
http://github.com/takahashikzn/eclipse-themes/releases/tag/v2.2.0-mars

**Comment by Mikanoshi** [comment]
@takahashikzn
Working :+1:  Finally pretty UI is back.

**Comment by lowne** [comment]
@takahashikzn thanks! \o/

**Comment by zaxeer** [comment]
Hi 
I have today tried to Install and use it with Eclispe Mars RC1, but still same issue. Can this update be installed by Update URL as i see its not yet in Eclispe Market?
Thanks
Zaheer

**Comment by jeeeyul** [comment]
I will release a new version for Eclipse Mars in next week. (I hope) Currently I am so busy, I can't review API changes and safeness of the pull requests for just now.

**Comment by nodj** [comment]
Great to read =) I'm sad to face my ugly eclipse everyday without this awesome plugin!
Thanks for your work!

**Comment by jeeeyul** [comment]
First beta for Mars is available at:
`http://eclipse.jeeeyul.net/beta-update`

**Comment by takahashikzn** [comment]
works fine

**Comment by zaxeer** [comment]
Ya its working fine, but still need a new install by marketplace and then update.
But thanks for your commitment with this plugin makes my java life colorful :+1:
