### ISSUE TITLE
Eclipse Mars M6 Fail to start with Plugin

### ISSUE THREAD

**Issue by zaxeer** [jeeeyul/eclipse-themes#233]
Hello jeeeyul,

I am using you pluging form very long time, and recently i try to switch to eclipse-jee-mars-M6-win32-x86_64 and after setting your plugin and restarting eclipse have errors. I think in workspace/meta/logs some exceptions will be helpful.

Thanks for fixing.
Regards
Zaheer

**Comment by matthias-fue** [comment]
This is probably a duplicate of #229
