### ISSUE TITLE
ToolBarCSSPropertyHandler can't play an effective role

### ISSUE THREAD

**Issue by ren1018023** [jeeeyul/eclipse-themes#235]
Why can't change text color of toolbar by use of jtool-item-color?

**Comment by jeeeyul** [comment]
That's SWT bug. see [Eclipse bug 443156](https://bugs.eclipse.org/bugs/show_bug.cgi?id=443156)

I reported it and post fix for SWT/Cocoa. But nobody seems care this problem.
Maybe it is too minor problem.

I used walk around that I could find, but it is not works for Windows 8.

**Comment by ren1018023** [comment]
walk around for other Platforms(includes Win7 or below):

toolbar.setForeground(newColor);

for(ToolItem item : toolbar.getItems()){
    String temp = item.getText();
    item.setText("");
    item.setText(temp);
}
That has no effect in win7.
