### ISSUE TITLE
Exporting of packages by plugin net.jeeeyul.eclipse.themes_2.2.0.I20140916-113709

### ISSUE THREAD

**Issue by avc2cob** [jeeeyul/eclipse-themes#236]
The net.jeeeyul.eclipse.themes plugin exports the following packages.

com.google.common.annotations,
com.google.common.base,
com.google.common.base.internal,
com.google.common.cache,
com.google.common.collect,
com.google.common.escape,
com.google.common.eventbus,
com.google.common.hash,
com.google.common.html,
com.google.common.io,
com.google.common.math,
com.google.common.net,
com.google.common.primitives,
com.google.common.reflect,
com.google.common.util.concurrent,
com.google.common.xml,
org.eclipse.xtend.lib,
org.eclipse.xtend.lib.annotations,
org.eclipse.xtend2.lib,
org.eclipse.xtext.xbase.lib,
org.eclipse.xtext.xbase.lib.internal,
org.eclipse.xtext.xbase.lib.util

If plug-ins use import package to access these packages, based on the order of resolution by eclipse, either the correct versions from the target or this incorrectly exported ones might be used.

Please fix this issues so that the downstream plug-ins do not refer to these plug-ins. The Access rules have to be changed and they have to be made forbidden.
http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Fguide%2Ftools%2Feditors%2Fmanifest_editor%2Faccess_rules.htm

**Comment by jeeeyul** [comment]
It's fixed

**Comment by avc2cob** [comment]
Can you please fix this in Kepler also. ?

**Comment by avc2cob** [comment]
Could you please also fix this in the Kepler version also ?
