### ISSUE TITLE
Tab height must be at least 31 in eclipse 4.5 mars, was previously 27

### ISSUE THREAD

**Issue by galan** [jeeeyul/eclipse-themes#240]
Hi, as the title describes, in the previous version of eclipse, I could reduce the  tab-height to 27, but now it is locked at 31. Is there a way to reduce the size in eclipse 4.5?

I'm using Xubuntu 15.04 as OS, and the just released eclipse Version: Mars Release (4.5.0), Build id: 20150621-1200.
Jeeeyul's Themes 2.3.0.I20150604-134826 net.jeeeyul.eclipse.themes.feature.feature.group

**Comment by renataogarcia** [comment]
I had this issue too and I've added some instructions to the [wiki](https://github.com/jeeeyul/eclipse-themes/wiki/Linux-Huge-Toolbar-Problem#gtk-3) on how to fix it.

**Comment by travnick** [comment]
but as far as I can see eclipse uses gtk3 instead of gtk2.

**Comment by renataogarcia** [comment]
@travnick That's correct - the info I've added to the wiki is for GTK3 (see GTK 3 section).

**Comment by renataogarcia** [comment]
I've updated the wiki with more details.

**Comment by galan** [comment]
Work for me, thanks for your addition!
