### ISSUE TITLE
Cannot find "Launch GTK 2.0 RC Wizard"

### ISSUE THREAD

**Issue by rulatir** [jeeeyul/eclipse-themes#243]
http://tiny.pl/gxq4r says:

> After installation of Jeeeyul's Eclipse Themes, You can find Launch GTK 2.0 RC Wizard from toolbar menu.

Well, I can't.

I'm not sure I understand what a "toolbar menu" is. Is it the context menu that shows when I right click on the toolbar? If so, I can only see one entry in this menu: "Restore hidden toolbar entries".

If this is a menu that shows when left-clicking on a toolbar button that is supposed to show when Jeeeyul's Eclipse Themes are installed, then the problem is that this toolbar button is not present at all, and I don't know how to enable it.

Using Mars PHP IDE fresh install.

**Comment by rulatir** [comment]
Ahh, alright. Had to restart Eclipse after enabling the button in Customize Perspective.

**Comment by renataogarcia** [comment]
Note that if you are using Mars, it will probably be using GTK3, so the "GTK 2.0 RC Wizard" won't help here. You need to follow the instructions from the GTK3 section.
