### ISSUE TITLE
Not appearing in Market for Neon

### ISSUE THREAD

**Issue by zaxeer** [jeeeyul/eclipse-themes#260]
Is there some compatibility issues that i don't see anymore this tool appearing in eclipse market space. Before it was there when i search "theme".

Thanks for great Themes.

**Comment by ncelerier** [comment]
When I search for "theme" I can see it. 

I'm using it with 4.6.0 and it is working fine for me.

**Comment by ncelerier** [comment]
But indeed if you search from Eclipse, it doesn't seem to show up :-(

If you want to install it, you can drag and drop the "Install" button of the plugin from your browser into your Eclipse. Note that you might need to install the "Eclipse Xtend" plugin first.

**Comment by zaxeer** [comment]
Thanks for your reply it installed in neon.3 but only be drag Install button. But as not appearing in marketplace made me thought may be not compatible anymore.
