### ISSUE TITLE
Cannot install Jeeeyul's Theme 2.3 on Eclipse 2020-03 (4.15)

### ISSUE THREAD

**Issue by Veroni23** [jeeeyul/eclipse-themes#274]
When installing on Eclipse 2020-03 via the marketplace, the Installation cannot complete as requested due to this error:

Missing requirement: Jeeeyul's Themes 2.3.12.I20200722-112020 (net.jeeeyul.eclipse.themes.feature.feature.group 2.3.12.I20200722-112020) requires 'org.eclipse.equinox.p2.iu; org.eclipse.xtend.lib 2.11.0' but it could not be found

The alternate proposal to make the installation  compatible to my eclipse by installing 
Jeeeyul's Themes	2.2.0.I20141210-114528	net.jeeeyul.eclipse.themes.feature.feature.group	Jeeeyul@gmail.com
    SWTend	2.2.6.I20200702-084710	net.jeeeyul.swtend.feature.feature.group	jeeeyul@gmail.com
does not work because of this bug:

When using this version to set the Window Background, this error is shown: 
`java.lang.NoSuchMethodError: org.eclipse.e4.ui.css.swt.helpers.CSSSWTColorHelper.getRGB(Lorg/w3c/dom/css/CSSValue;)Lorg/eclipse/swt/graphics/RGB;
	at net.jeeeyul.eclipse.themes.css.internal.handlers.JTabCSSPropertyHandler.applyCSSProperty(JTabCSSPropertyHandler.java:679)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyCSSProperty(AbstractCSSEngine.java:746)
...`
That error has been fixed already as I saw from the Issues. Is there a compatible version with that bug fix for Eclipse 4.15?

**Comment by ncelerier** [comment]
Maybe you could try to install Xtend manually first, then Jeeeyul's theme second.
There was this same kind of error some time ago and it did the trick for me ;-)

**Comment by Veroni23** [comment]
That worked, thank you!
