### ISSUE TITLE
Theme initally not applied when using Java > Version 9

### ISSUE THREAD

**Issue by metacodez** [jeeeyul/eclipse-themes#275]
First of all,  jeeeyul eclipse-themes are my absolute favourite Eclipse Themes! 

Though I encountered an issue when running starting Eclipse with a Java version > 9 on Windows 10 as well as on Arch Linux:

The Theme is not applied after Eclipse-Startup. I have to go into "`Preference` --> `General` --> `Appearance` --> `Jeeyul's Themes`" and hit `Apply` for the Theme to show up, even though my default theme is set to `Jeeyul's Themes`. In contrast, starting Eclipse with a Java 9 everything works fine.

Thanks beforehand & best regards,
Siegfried

**Comment by kuschuermann** [comment]
Had the same issue (Debian 10 Linux, Java 11), just upgraded and **this fixed it**. Thank you!!
