### ISSUE TITLE
https://eclipse.jeeeul.net/update is down sind December 13th, 2024

### ISSUE THREAD

**Issue by y0016408** [jeeeyul/eclipse-themes#283]
Hi all,

since Friedy, December 13th, 2024, the server https://eclipse.jeeeul.net/update is down. Please tell, when this server will be running again? Our software team needs this server. We are installing eclipse using the oomph-configuration, and when the server is down the installation process stops abruptly.

Kind regards,
Sergej

**Comment by jeeeyul** [comment]
@y0016408 Thanks for report, the domain will be available soon.
